apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- destinationrule-productpage.yaml
- destinationrule-reviews.yaml
- destinationrule-ratings.yaml
- destinationrule-details.yaml
